-- +goose Up
CREATE TABLE IF NOT EXISTS app_country (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    currency TEXT
);

-- +goose Down
DROP TABLE IF EXISTS app_country;
