### api info
GET {{domain}}/

### health
GET {{domain}}/health

### auth/register
POST {{domain}}/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password123"
  }

### auth/login
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### auth/profile
GET {{domain}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzUwOTE5ODA3LCJpYXQiOjE3NTA4MzM0MDd9.IyYmvCrpC3PyonSwJjs4dmSoM7QqyMAnpoXa88dhbYA

### countries
GET {{domain}}/api/v1/place/countries

### cities
GET {{domain}}/api/v1/place/cities/country/1

### near 5 places
GET {{domain}}/api/v1/place/places/near?long=71.408771&lat=51.162030&limit=5&radius=5000

### place detail
GET {{domain}}/api/v1/place/places/1

### random places
GET {{domain}}/api/v1/place/places/random

### random places country
GET {{domain}}/api/v1/place/places/random?country=1

### random places city
GET {{domain}}/api/v1/place/places/random?city=1

### places list in city
GET {{domain}}/api/v1/place/places/city/1
