### countries
GET {{domain}}/place/countries

### cities
GET {{domain}}/place/cities/country/1

### near 5 places
GET {{domain}}/place/places/near?long=71.408771&lat=51.162030&limit=5&radius=5000

### place detail
GET {{domain}}/place/places/1

### random places
GET {{domain}}/place/places/random

### random places country
GET {{domain}}/place/places/random?country=1

### random places city
GET {{domain}}/place/places/random?city=2

### places list in city
GET {{domain}}/place/places/city/1
